In [2]:
import pandas as pd
import numpy as np 

df = pd.read_csv('Countries.csv')
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [3]:
# WHICH COUNTRY HAS HIGHEST POPULATION
df[df['population'] == df['population'].max()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister

In [4]:
df[df['population'] == df['population'].max()]['country']

75    India
Name: country, dtype: object

In [5]:
# WHAT IS THE CAPITAL OF COUNTRY WHICH HAVE HIGHEST POPULATION
df[df['population'] == df['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [6]:
# WHICH COUNTRY HAS LEAST POPULATION
df[df['population'] == df['population'].min()]['country']

179    Tuvalu
Name: country, dtype: object

In [9]:
# WHAT IS THE CAPITAL OF COUNTRY WHICH HAVE LEAST POPULATION
df[df['population'] == df['population'].min()]['capital_city']

179    Funafuti
Name: capital_city, dtype: object

In [13]:
# TOP 5 COUNTRY WHICH HAVE HIGHEST DEMOCRATIC SCORE
df.nlargest(5,'democracy_score')

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [14]:
df.nlargest(5,'democracy_score')['country']

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [29]:
# HOW MANY TOTAL REGIONS ARE THERE
count = df['region'].count()
print(count)

194

In [30]:
# HOW MANY COUNTRIES LIE IN EASTER EUROPE REGION
df[df['region'] == "Eastern Europe"].count()

country             10
country_long        10
currency            10
capital_city        10
region              10
                    ..
democracy_score     10
democracy_type      10
median_age          10
political_leader     9
title                9
Length: 64, dtype: int64

In [48]:
# WHO IS THE LEADER OF 2nd HIGHEST POPULATED COUNTRY
df[df['population'] == df['population'].nlargest(2).iloc[1]]['political_leader']

34    Xi Jinping
Name: political_leader, dtype: object

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [49]:
# how many countries are there whoes political leaders are unknown
df[df['political_leader'].isna()]['country'].count()

np.int64(7)

In [50]:
#how many country have Republic in their full name
count = 0
def counting(txt):
    global count 
    if 'republic' in txt.lower():
        count+= 1
    return txt
df['country_long'] = df['country_long'].apply(counting)
print(count)

125

In [52]:
#which country in african region has highest population
africa_df = df[df['continent'] == 'Africa']

In [53]:
africa_df[africa_df['population'] == africa_df['population'].max()]['country']

125    Nigeria
Name: country, dtype: object